// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relationship

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelationshipService creates a new instance of MockRelationshipService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationshipService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationshipService {
	mock := &MockRelationshipService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelationshipService is an autogenerated mock type for the RelationshipService type
type MockRelationshipService struct {
	mock.Mock
}

type MockRelationshipService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationshipService) EXPECT() *MockRelationshipService_Expecter {
	return &MockRelationshipService_Expecter{mock: &_m.Mock}
}

// FollowUser provides a mock function for the type MockRelationshipService
func (_mock *MockRelationshipService) FollowUser(ctx context.Context, userID string, targetUserID string) error {
	ret := _mock.Called(ctx, userID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for FollowUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelationshipService_FollowUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FollowUser'
type MockRelationshipService_FollowUser_Call struct {
	*mock.Call
}

// FollowUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - targetUserID string
func (_e *MockRelationshipService_Expecter) FollowUser(ctx interface{}, userID interface{}, targetUserID interface{}) *MockRelationshipService_FollowUser_Call {
	return &MockRelationshipService_FollowUser_Call{Call: _e.mock.On("FollowUser", ctx, userID, targetUserID)}
}

func (_c *MockRelationshipService_FollowUser_Call) Run(run func(ctx context.Context, userID string, targetUserID string)) *MockRelationshipService_FollowUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRelationshipService_FollowUser_Call) Return(err error) *MockRelationshipService_FollowUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelationshipService_FollowUser_Call) RunAndReturn(run func(ctx context.Context, userID string, targetUserID string) error) *MockRelationshipService_FollowUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnFollowUSer provides a mock function for the type MockRelationshipService
func (_mock *MockRelationshipService) UnFollowUSer(ctx context.Context, userID string, targetUserID string) error {
	ret := _mock.Called(ctx, userID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for UnFollowUSer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelationshipService_UnFollowUSer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnFollowUSer'
type MockRelationshipService_UnFollowUSer_Call struct {
	*mock.Call
}

// UnFollowUSer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - targetUserID string
func (_e *MockRelationshipService_Expecter) UnFollowUSer(ctx interface{}, userID interface{}, targetUserID interface{}) *MockRelationshipService_UnFollowUSer_Call {
	return &MockRelationshipService_UnFollowUSer_Call{Call: _e.mock.On("UnFollowUSer", ctx, userID, targetUserID)}
}

func (_c *MockRelationshipService_UnFollowUSer_Call) Run(run func(ctx context.Context, userID string, targetUserID string)) *MockRelationshipService_UnFollowUSer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRelationshipService_UnFollowUSer_Call) Return(err error) *MockRelationshipService_UnFollowUSer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelationshipService_UnFollowUSer_Call) RunAndReturn(run func(ctx context.Context, userID string, targetUserID string) error) *MockRelationshipService_UnFollowUSer_Call {
	_c.Call.Return(run)
	return _c
}
