// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relationship

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelationshipRepository creates a new instance of MockRelationshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationshipRepository {
	mock := &MockRelationshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelationshipRepository is an autogenerated mock type for the RelationshipRepository type
type MockRelationshipRepository struct {
	mock.Mock
}

type MockRelationshipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationshipRepository) EXPECT() *MockRelationshipRepository_Expecter {
	return &MockRelationshipRepository_Expecter{mock: &_m.Mock}
}

// DeleteFollowingByUserIDAndTargetID provides a mock function for the type MockRelationshipRepository
func (_mock *MockRelationshipRepository) DeleteFollowingByUserIDAndTargetID(ctx context.Context, userID string, targetID string) error {
	ret := _mock.Called(ctx, userID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFollowingByUserIDAndTargetID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFollowingByUserIDAndTargetID'
type MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call struct {
	*mock.Call
}

// DeleteFollowingByUserIDAndTargetID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - targetID string
func (_e *MockRelationshipRepository_Expecter) DeleteFollowingByUserIDAndTargetID(ctx interface{}, userID interface{}, targetID interface{}) *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call {
	return &MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call{Call: _e.mock.On("DeleteFollowingByUserIDAndTargetID", ctx, userID, targetID)}
}

func (_c *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call) Run(run func(ctx context.Context, userID string, targetID string)) *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call) Return(err error) *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call) RunAndReturn(run func(ctx context.Context, userID string, targetID string) error) *MockRelationshipRepository_DeleteFollowingByUserIDAndTargetID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFollowing provides a mock function for the type MockRelationshipRepository
func (_mock *MockRelationshipRepository) InsertFollowing(ctx context.Context, following Following) error {
	ret := _mock.Called(ctx, following)

	if len(ret) == 0 {
		panic("no return value specified for InsertFollowing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Following) error); ok {
		r0 = returnFunc(ctx, following)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelationshipRepository_InsertFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFollowing'
type MockRelationshipRepository_InsertFollowing_Call struct {
	*mock.Call
}

// InsertFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - following Following
func (_e *MockRelationshipRepository_Expecter) InsertFollowing(ctx interface{}, following interface{}) *MockRelationshipRepository_InsertFollowing_Call {
	return &MockRelationshipRepository_InsertFollowing_Call{Call: _e.mock.On("InsertFollowing", ctx, following)}
}

func (_c *MockRelationshipRepository_InsertFollowing_Call) Run(run func(ctx context.Context, following Following)) *MockRelationshipRepository_InsertFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Following
		if args[1] != nil {
			arg1 = args[1].(Following)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelationshipRepository_InsertFollowing_Call) Return(err error) *MockRelationshipRepository_InsertFollowing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelationshipRepository_InsertFollowing_Call) RunAndReturn(run func(ctx context.Context, following Following) error) *MockRelationshipRepository_InsertFollowing_Call {
	_c.Call.Return(run)
	return _c
}
