// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"clone-instagram-service/internal/domain/model/user/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetFollowerUsersByUserID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetFollowerUsersByUserID(ctx context.Context, userID int) ([]user.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowerUsersByUserID")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]user.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetFollowerUsersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowerUsersByUserID'
type MockUserRepository_GetFollowerUsersByUserID_Call struct {
	*mock.Call
}

// GetFollowerUsersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepository_Expecter) GetFollowerUsersByUserID(ctx interface{}, userID interface{}) *MockUserRepository_GetFollowerUsersByUserID_Call {
	return &MockUserRepository_GetFollowerUsersByUserID_Call{Call: _e.mock.On("GetFollowerUsersByUserID", ctx, userID)}
}

func (_c *MockUserRepository_GetFollowerUsersByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepository_GetFollowerUsersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetFollowerUsersByUserID_Call) Return(users []user.User, err error) *MockUserRepository_GetFollowerUsersByUserID_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetFollowerUsersByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]user.User, error)) *MockUserRepository_GetFollowerUsersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowingUsersByUserID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetFollowingUsersByUserID(ctx context.Context, userID int) ([]user.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowingUsersByUserID")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]user.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetFollowingUsersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowingUsersByUserID'
type MockUserRepository_GetFollowingUsersByUserID_Call struct {
	*mock.Call
}

// GetFollowingUsersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepository_Expecter) GetFollowingUsersByUserID(ctx interface{}, userID interface{}) *MockUserRepository_GetFollowingUsersByUserID_Call {
	return &MockUserRepository_GetFollowingUsersByUserID_Call{Call: _e.mock.On("GetFollowingUsersByUserID", ctx, userID)}
}

func (_c *MockUserRepository_GetFollowingUsersByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepository_GetFollowingUsersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetFollowingUsersByUserID_Call) Return(users []user.User, err error) *MockUserRepository_GetFollowingUsersByUserID_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetFollowingUsersByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]user.User, error)) *MockUserRepository_GetFollowingUsersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByGoogleID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByGoogleID(ctx context.Context, googleID string) (user.User, bool, error) {
	ret := _mock.Called(ctx, googleID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByGoogleID")
	}

	var r0 user.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (user.User, bool, error)); ok {
		return returnFunc(ctx, googleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = returnFunc(ctx, googleID)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, googleID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, googleID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepository_GetUserByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByGoogleID'
type MockUserRepository_GetUserByGoogleID_Call struct {
	*mock.Call
}

// GetUserByGoogleID is a helper method to define mock.On call
//   - ctx context.Context
//   - googleID string
func (_e *MockUserRepository_Expecter) GetUserByGoogleID(ctx interface{}, googleID interface{}) *MockUserRepository_GetUserByGoogleID_Call {
	return &MockUserRepository_GetUserByGoogleID_Call{Call: _e.mock.On("GetUserByGoogleID", ctx, googleID)}
}

func (_c *MockUserRepository_GetUserByGoogleID_Call) Run(run func(ctx context.Context, googleID string)) *MockUserRepository_GetUserByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByGoogleID_Call) Return(user1 user.User, b bool, err error) *MockUserRepository_GetUserByGoogleID_Call {
	_c.Call.Return(user1, b, err)
	return _c
}

func (_c *MockUserRepository_GetUserByGoogleID_Call) RunAndReturn(run func(ctx context.Context, googleID string) (user.User, bool, error)) *MockUserRepository_GetUserByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(ctx context.Context, userID int) (user.User, bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 user.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (user.User, bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user1 user.User, b bool, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user1, b, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (user.User, bool, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) InsertUser(ctx context.Context, user1 user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockUserRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 user.User
func (_e *MockUserRepository_Expecter) InsertUser(ctx interface{}, user1 interface{}) *MockUserRepository_InsertUser_Call {
	return &MockUserRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user1)}
}

func (_c *MockUserRepository_InsertUser_Call) Run(run func(ctx context.Context, user1 user.User)) *MockUserRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_InsertUser_Call) Return(err error) *MockUserRepository_InsertUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_InsertUser_Call) RunAndReturn(run func(ctx context.Context, user1 user.User) error) *MockUserRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}
