// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"clone-instagram-service/internal/domain/model/aggregate"
	"clone-instagram-service/internal/domain/model/auth"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetUserProfileByGoogleSubID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserProfileByGoogleSubID(ctx context.Context, googleSubID string) (aggregate.UserProfile, error) {
	ret := _mock.Called(ctx, googleSubID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfileByGoogleSubID")
	}

	var r0 aggregate.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (aggregate.UserProfile, error)); ok {
		return returnFunc(ctx, googleSubID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) aggregate.UserProfile); ok {
		r0 = returnFunc(ctx, googleSubID)
	} else {
		r0 = ret.Get(0).(aggregate.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, googleSubID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserProfileByGoogleSubID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfileByGoogleSubID'
type MockUserService_GetUserProfileByGoogleSubID_Call struct {
	*mock.Call
}

// GetUserProfileByGoogleSubID is a helper method to define mock.On call
//   - ctx context.Context
//   - googleSubID string
func (_e *MockUserService_Expecter) GetUserProfileByGoogleSubID(ctx interface{}, googleSubID interface{}) *MockUserService_GetUserProfileByGoogleSubID_Call {
	return &MockUserService_GetUserProfileByGoogleSubID_Call{Call: _e.mock.On("GetUserProfileByGoogleSubID", ctx, googleSubID)}
}

func (_c *MockUserService_GetUserProfileByGoogleSubID_Call) Run(run func(ctx context.Context, googleSubID string)) *MockUserService_GetUserProfileByGoogleSubID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserProfileByGoogleSubID_Call) Return(userProfile aggregate.UserProfile, err error) *MockUserService_GetUserProfileByGoogleSubID_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockUserService_GetUserProfileByGoogleSubID_Call) RunAndReturn(run func(ctx context.Context, googleSubID string) (aggregate.UserProfile, error)) *MockUserService_GetUserProfileByGoogleSubID_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithGoogleAccessCode provides a mock function for the type MockUserService
func (_mock *MockUserService) LoginWithGoogleAccessCode(ctx context.Context, googleAccessCode string) (auth.AccessCodeResponse, error) {
	ret := _mock.Called(ctx, googleAccessCode)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithGoogleAccessCode")
	}

	var r0 auth.AccessCodeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.AccessCodeResponse, error)); ok {
		return returnFunc(ctx, googleAccessCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.AccessCodeResponse); ok {
		r0 = returnFunc(ctx, googleAccessCode)
	} else {
		r0 = ret.Get(0).(auth.AccessCodeResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, googleAccessCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_LoginWithGoogleAccessCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithGoogleAccessCode'
type MockUserService_LoginWithGoogleAccessCode_Call struct {
	*mock.Call
}

// LoginWithGoogleAccessCode is a helper method to define mock.On call
//   - ctx context.Context
//   - googleAccessCode string
func (_e *MockUserService_Expecter) LoginWithGoogleAccessCode(ctx interface{}, googleAccessCode interface{}) *MockUserService_LoginWithGoogleAccessCode_Call {
	return &MockUserService_LoginWithGoogleAccessCode_Call{Call: _e.mock.On("LoginWithGoogleAccessCode", ctx, googleAccessCode)}
}

func (_c *MockUserService_LoginWithGoogleAccessCode_Call) Run(run func(ctx context.Context, googleAccessCode string)) *MockUserService_LoginWithGoogleAccessCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_LoginWithGoogleAccessCode_Call) Return(accessCodeResponse auth.AccessCodeResponse, err error) *MockUserService_LoginWithGoogleAccessCode_Call {
	_c.Call.Return(accessCodeResponse, err)
	return _c
}

func (_c *MockUserService_LoginWithGoogleAccessCode_Call) RunAndReturn(run func(ctx context.Context, googleAccessCode string) (auth.AccessCodeResponse, error)) *MockUserService_LoginWithGoogleAccessCode_Call {
	_c.Call.Return(run)
	return _c
}
