// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"clone-instagram-service/internal/domain/model/user/entity"
	"context"

	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthMiddleWare creates a new instance of MockAuthMiddleWare. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthMiddleWare(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthMiddleWare {
	mock := &MockAuthMiddleWare{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthMiddleWare is an autogenerated mock type for the AuthMiddleWare type
type MockAuthMiddleWare struct {
	mock.Mock
}

type MockAuthMiddleWare_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthMiddleWare) EXPECT() *MockAuthMiddleWare_Expecter {
	return &MockAuthMiddleWare_Expecter{mock: &_m.Mock}
}

// AuthWithUser provides a mock function for the type MockAuthMiddleWare
func (_mock *MockAuthMiddleWare) AuthWithUser(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for AuthWithUser")
	}

	var r0 echo.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}
	return r0
}

// MockAuthMiddleWare_AuthWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthWithUser'
type MockAuthMiddleWare_AuthWithUser_Call struct {
	*mock.Call
}

// AuthWithUser is a helper method to define mock.On call
//   - next echo.HandlerFunc
func (_e *MockAuthMiddleWare_Expecter) AuthWithUser(next interface{}) *MockAuthMiddleWare_AuthWithUser_Call {
	return &MockAuthMiddleWare_AuthWithUser_Call{Call: _e.mock.On("AuthWithUser", next)}
}

func (_c *MockAuthMiddleWare_AuthWithUser_Call) Run(run func(next echo.HandlerFunc)) *MockAuthMiddleWare_AuthWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(echo.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthMiddleWare_AuthWithUser_Call) Return(handlerFunc echo.HandlerFunc) *MockAuthMiddleWare_AuthWithUser_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockAuthMiddleWare_AuthWithUser_Call) RunAndReturn(run func(next echo.HandlerFunc) echo.HandlerFunc) *MockAuthMiddleWare_AuthWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfoByAccessToken provides a mock function for the type MockAuthMiddleWare
func (_mock *MockAuthMiddleWare) GetUserInfoByAccessToken(ctx context.Context, accessToken string) (user.User, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfoByAccessToken")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (user.User, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthMiddleWare_GetUserInfoByAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfoByAccessToken'
type MockAuthMiddleWare_GetUserInfoByAccessToken_Call struct {
	*mock.Call
}

// GetUserInfoByAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockAuthMiddleWare_Expecter) GetUserInfoByAccessToken(ctx interface{}, accessToken interface{}) *MockAuthMiddleWare_GetUserInfoByAccessToken_Call {
	return &MockAuthMiddleWare_GetUserInfoByAccessToken_Call{Call: _e.mock.On("GetUserInfoByAccessToken", ctx, accessToken)}
}

func (_c *MockAuthMiddleWare_GetUserInfoByAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockAuthMiddleWare_GetUserInfoByAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthMiddleWare_GetUserInfoByAccessToken_Call) Return(user1 user.User, err error) *MockAuthMiddleWare_GetUserInfoByAccessToken_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthMiddleWare_GetUserInfoByAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (user.User, error)) *MockAuthMiddleWare_GetUserInfoByAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
