// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package news_feed

import (
	"clone-instagram-service/internal/domain/model/news_feed/aggregate"
	"clone-instagram-service/internal/domain/model/news_feed/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNewsFeedRepository creates a new instance of MockNewsFeedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNewsFeedRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNewsFeedRepository {
	mock := &MockNewsFeedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNewsFeedRepository is an autogenerated mock type for the NewsFeedRepository type
type MockNewsFeedRepository struct {
	mock.Mock
}

type MockNewsFeedRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNewsFeedRepository) EXPECT() *MockNewsFeedRepository_Expecter {
	return &MockNewsFeedRepository_Expecter{mock: &_m.Mock}
}

// GetNewsFeedByFilter provides a mock function for the type MockNewsFeedRepository
func (_mock *MockNewsFeedRepository) GetNewsFeedByFilter(ctx context.Context, filter entity.NewsFeedFilter) ([]aggregate.NewsFeed, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsFeedByFilter")
	}

	var r0 []aggregate.NewsFeed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.NewsFeedFilter) ([]aggregate.NewsFeed, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.NewsFeedFilter) []aggregate.NewsFeed); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aggregate.NewsFeed)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.NewsFeedFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNewsFeedRepository_GetNewsFeedByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsFeedByFilter'
type MockNewsFeedRepository_GetNewsFeedByFilter_Call struct {
	*mock.Call
}

// GetNewsFeedByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entity.NewsFeedFilter
func (_e *MockNewsFeedRepository_Expecter) GetNewsFeedByFilter(ctx interface{}, filter interface{}) *MockNewsFeedRepository_GetNewsFeedByFilter_Call {
	return &MockNewsFeedRepository_GetNewsFeedByFilter_Call{Call: _e.mock.On("GetNewsFeedByFilter", ctx, filter)}
}

func (_c *MockNewsFeedRepository_GetNewsFeedByFilter_Call) Run(run func(ctx context.Context, filter entity.NewsFeedFilter)) *MockNewsFeedRepository_GetNewsFeedByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.NewsFeedFilter
		if args[1] != nil {
			arg1 = args[1].(entity.NewsFeedFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNewsFeedRepository_GetNewsFeedByFilter_Call) Return(newsFeeds []aggregate.NewsFeed, err error) *MockNewsFeedRepository_GetNewsFeedByFilter_Call {
	_c.Call.Return(newsFeeds, err)
	return _c
}

func (_c *MockNewsFeedRepository_GetNewsFeedByFilter_Call) RunAndReturn(run func(ctx context.Context, filter entity.NewsFeedFilter) ([]aggregate.NewsFeed, error)) *MockNewsFeedRepository_GetNewsFeedByFilter_Call {
	_c.Call.Return(run)
	return _c
}
