// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package news_feed

import (
	"clone-instagram-service/internal/domain/model/news_feed/aggregate"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNewsFeedService creates a new instance of MockNewsFeedService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNewsFeedService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNewsFeedService {
	mock := &MockNewsFeedService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNewsFeedService is an autogenerated mock type for the NewsFeedService type
type MockNewsFeedService struct {
	mock.Mock
}

type MockNewsFeedService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNewsFeedService) EXPECT() *MockNewsFeedService_Expecter {
	return &MockNewsFeedService_Expecter{mock: &_m.Mock}
}

// GetNewsFeedByUserID provides a mock function for the type MockNewsFeedService
func (_mock *MockNewsFeedService) GetNewsFeedByUserID(ctx context.Context, userID int) ([]aggregate.NewsFeed, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsFeedByUserID")
	}

	var r0 []aggregate.NewsFeed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]aggregate.NewsFeed, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []aggregate.NewsFeed); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aggregate.NewsFeed)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNewsFeedService_GetNewsFeedByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsFeedByUserID'
type MockNewsFeedService_GetNewsFeedByUserID_Call struct {
	*mock.Call
}

// GetNewsFeedByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNewsFeedService_Expecter) GetNewsFeedByUserID(ctx interface{}, userID interface{}) *MockNewsFeedService_GetNewsFeedByUserID_Call {
	return &MockNewsFeedService_GetNewsFeedByUserID_Call{Call: _e.mock.On("GetNewsFeedByUserID", ctx, userID)}
}

func (_c *MockNewsFeedService_GetNewsFeedByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockNewsFeedService_GetNewsFeedByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNewsFeedService_GetNewsFeedByUserID_Call) Return(newsFeeds []aggregate.NewsFeed, err error) *MockNewsFeedService_GetNewsFeedByUserID_Call {
	_c.Call.Return(newsFeeds, err)
	return _c
}

func (_c *MockNewsFeedService_GetNewsFeedByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]aggregate.NewsFeed, error)) *MockNewsFeedService_GetNewsFeedByUserID_Call {
	_c.Call.Return(run)
	return _c
}
