// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"clone-instagram-service/internal/domain/model/notification/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// GetAllNotificationsByUserID provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) GetAllNotificationsByUserID(ctx context.Context, userID int) ([]entity.NotificationResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotificationsByUserID")
	}

	var r0 []entity.NotificationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.NotificationResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.NotificationResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NotificationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationService_GetAllNotificationsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotificationsByUserID'
type MockNotificationService_GetAllNotificationsByUserID_Call struct {
	*mock.Call
}

// GetAllNotificationsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationService_Expecter) GetAllNotificationsByUserID(ctx interface{}, userID interface{}) *MockNotificationService_GetAllNotificationsByUserID_Call {
	return &MockNotificationService_GetAllNotificationsByUserID_Call{Call: _e.mock.On("GetAllNotificationsByUserID", ctx, userID)}
}

func (_c *MockNotificationService_GetAllNotificationsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationService_GetAllNotificationsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationService_GetAllNotificationsByUserID_Call) Return(notificationResponses []entity.NotificationResponse, err error) *MockNotificationService_GetAllNotificationsByUserID_Call {
	_c.Call.Return(notificationResponses, err)
	return _c
}

func (_c *MockNotificationService_GetAllNotificationsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]entity.NotificationResponse, error)) *MockNotificationService_GetAllNotificationsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllNotificationsAsReadByUserID provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) MarkAllNotificationsAsReadByUserID(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllNotificationsAsReadByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationService_MarkAllNotificationsAsReadByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllNotificationsAsReadByUserID'
type MockNotificationService_MarkAllNotificationsAsReadByUserID_Call struct {
	*mock.Call
}

// MarkAllNotificationsAsReadByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationService_Expecter) MarkAllNotificationsAsReadByUserID(ctx interface{}, userID interface{}) *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call {
	return &MockNotificationService_MarkAllNotificationsAsReadByUserID_Call{Call: _e.mock.On("MarkAllNotificationsAsReadByUserID", ctx, userID)}
}

func (_c *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call) Return(err error) *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockNotificationService_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Return(run)
	return _c
}
