// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"clone-instagram-service/internal/domain/model/relationship/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationSubscriber creates a new instance of MockNotificationSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSubscriber {
	mock := &MockNotificationSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSubscriber is an autogenerated mock type for the NotificationSubscriber type
type MockNotificationSubscriber struct {
	mock.Mock
}

type MockNotificationSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSubscriber) EXPECT() *MockNotificationSubscriber_Expecter {
	return &MockNotificationSubscriber_Expecter{mock: &_m.Mock}
}

// SubscribeFollowing provides a mock function for the type MockNotificationSubscriber
func (_mock *MockNotificationSubscriber) SubscribeFollowing(callback func(ctx context.Context, message relationship.FollowingTopicMessage) error) error {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeFollowing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(ctx context.Context, message relationship.FollowingTopicMessage) error) error); ok {
		r0 = returnFunc(callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSubscriber_SubscribeFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeFollowing'
type MockNotificationSubscriber_SubscribeFollowing_Call struct {
	*mock.Call
}

// SubscribeFollowing is a helper method to define mock.On call
//   - callback func(ctx context.Context, message relationship.FollowingTopicMessage) error
func (_e *MockNotificationSubscriber_Expecter) SubscribeFollowing(callback interface{}) *MockNotificationSubscriber_SubscribeFollowing_Call {
	return &MockNotificationSubscriber_SubscribeFollowing_Call{Call: _e.mock.On("SubscribeFollowing", callback)}
}

func (_c *MockNotificationSubscriber_SubscribeFollowing_Call) Run(run func(callback func(ctx context.Context, message relationship.FollowingTopicMessage) error)) *MockNotificationSubscriber_SubscribeFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(ctx context.Context, message relationship.FollowingTopicMessage) error
		if args[0] != nil {
			arg0 = args[0].(func(ctx context.Context, message relationship.FollowingTopicMessage) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotificationSubscriber_SubscribeFollowing_Call) Return(err error) *MockNotificationSubscriber_SubscribeFollowing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSubscriber_SubscribeFollowing_Call) RunAndReturn(run func(callback func(ctx context.Context, message relationship.FollowingTopicMessage) error) error) *MockNotificationSubscriber_SubscribeFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeFollowingWithUserID provides a mock function for the type MockNotificationSubscriber
func (_mock *MockNotificationSubscriber) SubscribeFollowingWithUserID(ctx context.Context, userID int, callback func(ctx context.Context, message relationship.FollowingTopicMessage) error) error {
	ret := _mock.Called(ctx, userID, callback)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeFollowingWithUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, func(ctx context.Context, message relationship.FollowingTopicMessage) error) error); ok {
		r0 = returnFunc(ctx, userID, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSubscriber_SubscribeFollowingWithUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeFollowingWithUserID'
type MockNotificationSubscriber_SubscribeFollowingWithUserID_Call struct {
	*mock.Call
}

// SubscribeFollowingWithUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - callback func(ctx context.Context, message relationship.FollowingTopicMessage) error
func (_e *MockNotificationSubscriber_Expecter) SubscribeFollowingWithUserID(ctx interface{}, userID interface{}, callback interface{}) *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call {
	return &MockNotificationSubscriber_SubscribeFollowingWithUserID_Call{Call: _e.mock.On("SubscribeFollowingWithUserID", ctx, userID, callback)}
}

func (_c *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call) Run(run func(ctx context.Context, userID int, callback func(ctx context.Context, message relationship.FollowingTopicMessage) error)) *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 func(ctx context.Context, message relationship.FollowingTopicMessage) error
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, message relationship.FollowingTopicMessage) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call) Return(err error) *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call) RunAndReturn(run func(ctx context.Context, userID int, callback func(ctx context.Context, message relationship.FollowingTopicMessage) error) error) *MockNotificationSubscriber_SubscribeFollowingWithUserID_Call {
	_c.Call.Return(run)
	return _c
}
