// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"clone-instagram-service/internal/domain/model/notification/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// GetAllNotificationsByUserID provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) GetAllNotificationsByUserID(ctx context.Context, userID int) ([]entity.Notification, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotificationsByUserID")
	}

	var r0 []entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.Notification, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.Notification); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_GetAllNotificationsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotificationsByUserID'
type MockNotificationRepository_GetAllNotificationsByUserID_Call struct {
	*mock.Call
}

// GetAllNotificationsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationRepository_Expecter) GetAllNotificationsByUserID(ctx interface{}, userID interface{}) *MockNotificationRepository_GetAllNotificationsByUserID_Call {
	return &MockNotificationRepository_GetAllNotificationsByUserID_Call{Call: _e.mock.On("GetAllNotificationsByUserID", ctx, userID)}
}

func (_c *MockNotificationRepository_GetAllNotificationsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationRepository_GetAllNotificationsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_GetAllNotificationsByUserID_Call) Return(notifications []entity.Notification, err error) *MockNotificationRepository_GetAllNotificationsByUserID_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNotificationRepository_GetAllNotificationsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]entity.Notification, error)) *MockNotificationRepository_GetAllNotificationsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotficationByID provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) GetNotficationByID(ctx context.Context, notificationID int) (entity.Notification, bool, error) {
	ret := _mock.Called(ctx, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotficationByID")
	}

	var r0 entity.Notification
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (entity.Notification, bool, error)); ok {
		return returnFunc(ctx, notificationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) entity.Notification); ok {
		r0 = returnFunc(ctx, notificationID)
	} else {
		r0 = ret.Get(0).(entity.Notification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, notificationID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, notificationID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotificationRepository_GetNotficationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotficationByID'
type MockNotificationRepository_GetNotficationByID_Call struct {
	*mock.Call
}

// GetNotficationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationID int
func (_e *MockNotificationRepository_Expecter) GetNotficationByID(ctx interface{}, notificationID interface{}) *MockNotificationRepository_GetNotficationByID_Call {
	return &MockNotificationRepository_GetNotficationByID_Call{Call: _e.mock.On("GetNotficationByID", ctx, notificationID)}
}

func (_c *MockNotificationRepository_GetNotficationByID_Call) Run(run func(ctx context.Context, notificationID int)) *MockNotificationRepository_GetNotficationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_GetNotficationByID_Call) Return(notification entity.Notification, b bool, err error) *MockNotificationRepository_GetNotficationByID_Call {
	_c.Call.Return(notification, b, err)
	return _c
}

func (_c *MockNotificationRepository_GetNotficationByID_Call) RunAndReturn(run func(ctx context.Context, notificationID int) (entity.Notification, bool, error)) *MockNotificationRepository_GetNotficationByID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertNotification provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) InsertNotification(ctx context.Context, notification entity.Notification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for InsertNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Notification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_InsertNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertNotification'
type MockNotificationRepository_InsertNotification_Call struct {
	*mock.Call
}

// InsertNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notification entity.Notification
func (_e *MockNotificationRepository_Expecter) InsertNotification(ctx interface{}, notification interface{}) *MockNotificationRepository_InsertNotification_Call {
	return &MockNotificationRepository_InsertNotification_Call{Call: _e.mock.On("InsertNotification", ctx, notification)}
}

func (_c *MockNotificationRepository_InsertNotification_Call) Run(run func(ctx context.Context, notification entity.Notification)) *MockNotificationRepository_InsertNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Notification
		if args[1] != nil {
			arg1 = args[1].(entity.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_InsertNotification_Call) Return(err error) *MockNotificationRepository_InsertNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_InsertNotification_Call) RunAndReturn(run func(ctx context.Context, notification entity.Notification) error) *MockNotificationRepository_InsertNotification_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllNotificationsAsReadByUserID provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) MarkAllNotificationsAsReadByUserID(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllNotificationsAsReadByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllNotificationsAsReadByUserID'
type MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call struct {
	*mock.Call
}

// MarkAllNotificationsAsReadByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationRepository_Expecter) MarkAllNotificationsAsReadByUserID(ctx interface{}, userID interface{}) *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call {
	return &MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call{Call: _e.mock.On("MarkAllNotificationsAsReadByUserID", ctx, userID)}
}

func (_c *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call) Return(err error) *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockNotificationRepository_MarkAllNotificationsAsReadByUserID_Call {
	_c.Call.Return(run)
	return _c
}
